# Generated by Django 3.0.8 on 2020-08-12 02:15

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='body',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
